version: '3'

services:
  xxljob:
    image: voyo-xxljob:v2.4.2
    container_name: voyo-xxljob
    ports:
      - "8083:8083"
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: 10
    environment:
      - XXL_CONTEXT_PATH=/scrm-job-admin
      - XXL_MYSQL_HOST=xxxx
      - XXL_MYSQL_PORT=xxx
      - XXL_MYSQL_DB=xxxx
      - XXL_MYSQL_ACCOUNT=xxxx
      - XXL_MYSQL_PASSWORD=xxxx
      - XXL_ACCESS_TOKEN=xxxx
      - XXL_PORT=8083
    command: [
      "-Duser.timezone=Asia/Shanghai",
      "-Dfile.encoding=UTF-8",
      "-XX:MetaspaceSize=256M",
      "-XX:MaxMetaspaceSize=256M",
      "-Xmx512M",
      "/app.jar"
    ]
